base_model: microsoft/phi-1_5
base_model_config: microsoft/phi-1_5
model_type: AutoModelForCuasalLM
tokenizer_type: AutoTokenizer
load_in_8bit: false
load_in_4bit: false
strict: false
trust_remote_code: True
datasets:
  - path: LDJnr/Puffin
    type: sharegpt:chat
dataset_prepared_path: data/last_run_prepared
val_set_size: 0.00
adapter:
lora_model_dir:
sequence_len: 2048
max_packed_sequence_len:
lora_r:
lora_alpha:
lora_dropout:
lora_target_modules:
lora_target_linear:
lora_fan_in_fan_out:
hub_model_id: teknium/puffin-phi
wandb_project: puffin-phi
wandb_watch:
wandb_run_id: puffin-phi-1
wandb_log_model:
output_dir: ./puffin-phi
gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 3
optimizer: adamw_bnb_8bit
torchdistx_path:
lr_scheduler: cosine
learning_rate: 0.00002
train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: true
gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention: true
flash_attention:
gptq_groupsize:
gptq_model_v1:
warmup_steps: 300
eval_steps: "no"
save_strategy: "no"
save_steps:
debug:
deepspeed:
weight_decay: 0.01
#fsdp:
#  - full_shard
#  - auto_wrap
#fsdp_config:
#  fsdp_offload_params: false
#  fsdp_state_dict_type: FULL_STATE_DICT
#  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
  pad_token: "<pad>"
